image: Visual Studio 2019
init:
  - git config --global core.autocrlf true
branches:
  only:
    - master
    # We'll also build whenever there is a new commit on any branch starting with `features/`
    - /features\/.+/
build_script:
  - ps: |
      dotnet cake build.cake --bootstrap
      dotnet cake build.cake --pack
assembly_info:
  # No thank you, I'll do this myself
  patch: false
# We'll run the tests in the build script
test: off
# AppVeyor will create a release tag if a matching one does not exist
# hence triggering another build
skip_tags: true
skip_commits:
  files:
    - .editorconfig
    - LICENSE
    - README.md
    - docs/*
deploy:
  # The provider is case sensitive
  - provider: GitHub
    # By convention release versions start with `v`
    release: v$(APPVEYOR_BUILD_VERSION)
    auth_token:
      # Encrypted `GitHub` `PAT`
      # https://www.appveyor.com/docs/deployment/github/#provider-settings
      secure: AmCNluoUjQddLCZrNghd0XjLwFhrofDMF7UTdmJDLuK5g/+FKGfBr6IOIbN3hrRw
    artifact: packages
    draft: false
    prerelease: false
    on:
      branch: master
  - provider: NuGet
    server: https://www.nuget.org/api/v2/package
    api_key:
      # Encrypted `NuGet.org` token - https://www.nuget.org/account/ApiKeys
      # https://www.appveyor.com/docs/deployment/nuget/#provider-settings
      secure: R/FPkcohOwV7rSdAldncHGQVKQwZhNWUjlXYJeiNP0CbmPVdS3yqs2gpsS4XEwUj
    skip_symbols: false
    symbol_server: https://nuget.smbsrc.net/
    artifact: packages
    on:
      branch: master
  - provider: GitHub
    # By convention release versions start with `v`
    release: v$(APPVEYOR_BUILD_VERSION)
    auth_token:
      # Encrypted `GitHub` `PAT`
      # https://www.appveyor.com/docs/deployment/github/#provider-settings
      secure: AmCNluoUjQddLCZrNghd0XjLwFhrofDMF7UTdmJDLuK5g/+FKGfBr6IOIbN3hrRw
    artifact: packages
    draft: false
    prerelease: true
    on:
      branch: /features\/.+/
# Environment variables
environment:
  # No need to pre-warm the `NuGet` cache
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
# `install` will run before `build_script`
install:
  # `dotnet-wad-to-csv` is targeting `netcoreapp3.1`, so we can safely install the LTS `SDK`
  # The `SDK` is required to restore, build, publish... a `.NET Core` application
  # https://www.microsoft.com/net/download/windows
  - ps: .\build\dotnet-install.ps1
  - ps: dotnet tool install --global Cake.Tool --version 0.35.0
